# Generated by Django 4.2.6 on 2023-11-22 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Taller', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscripciontaller',
            old_name='fechaCreacion',
            new_name='fechaCompletado',
        ),
    ]
