# Generated by Django 4.2.6 on 2023-11-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taller', '0002_rename_fechacreacion_inscripciontaller_fechacompletado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripciontaller',
            name='fechaCompletado',
            field=models.DateTimeField(null=True),
        ),
    ]
